name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: forge --version

      - name: Run Forge fmt
        run: forge fmt --check
        id: fmt

      - name: Clean build and lib
        run: rm -rf out cache lib

      - name: Install forge-std
        run: forge install foundry-rs/forge-std

      - name: Install OpenZeppelin
        run: forge install OpenZeppelin/openzeppelin-contracts

      - name: Remove OpenZeppelin remappings.txt
        run: rm -f lib/openzeppelin-contracts/remappings.txt
        
      - name: List lib directory
        run: ls -lR lib

        - name: Debug - Check if files exist
          run: |
            echo "=== Checking if ReentrancyGuard.sol exists ==="
            ls -la lib/openzeppelin-contracts/contracts/security/ReentrancyGuard.sol || echo "NOT FOUND"
            
            echo "=== Checking remappings files ==="
            find . -name "remappings.txt" -exec echo "Found: {}" \; -exec cat {} \;
            
            echo "=== Foundry config ==="
            forge config --json | jq '.remappings'

        - name: Debug - Test remapping manually
          run: |
            echo "=== Testing remapping resolution ==="
            forge build --dry-run --remappings "@openzeppelin/=lib/openzeppelin-contracts/" || echo "DRY RUN FAILED"

      - name: Run Forge build
        run: forge build --sizes --remappings "@openzeppelin/=lib/openzeppelin-contracts/"

      - name: Run Forge tests
        run: forge test -vvv
        id: test